version: '3.8'

services:
  dont-forget-tasks:
    build: .
    # container_name: dont-forget-tasks
    depends_on:
      # - rabbitmq
      - redis
    environment:
      - RABBIT_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
    networks:
      - app_network
    ports:
      - '3002:3000'

  redis:
    image: redis:7-alpine
    # container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    name: dontforgetgateway_app_network
    # name: pocmsgateway_app_network
    external: true
