version: '3.8'

services:
  ms-node:
    build: .
    container_name: ms-node
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_URL=amqp://rabbitmq:5672
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
    networks:
      - app_network
    ports:
      - "3000:3000"

networks:
  app_network:
    name: pocmsgateway_app_network
    external: true
